### PR TITLE
Basic class Implementation that is shared between the micro-loan comm…

### PR DESCRIPTION
**Pull request by st2180**
…ands implementation.

### CODE REVIEW

**Comment by inariDeeTee** [comment]
Hi Shinichi,
Great work, looks really good. I did have some thoughts about how to better encapsulate Loan and Offer. I think interestRate and borrowingLength variables should be added to Loan and offerNumber removed. This means once an offer has been accepted and a Loan object created the relevant Offer object can be deleted without losing any information. Deleting Offer objects also means they can't be seen in MicroLoanMarketPlace so customers can only see offers that are available. Do you agree?
Thanks, Heather

**Comment by st2180** [comment]
Hi Heather, 

I would think duplication is one of the things that we should be careful of the most in Software. 
I think you are mentioning that we should make copies of an interestRate and a borrowingLength when a Loan is made, but how about the lendingAccount? Without the lendingAccount, a borrower can't repay. If we added the lendingAccount to the Loan, the Loan object would have almost all of the Offer's states. It is practically the same that the Loan has an Offer object inside, and it's also logically the same that the Offer has an offerNumber. If we do this, I'd be better that we completely combine the two classes into a big Loan class.

However, I made two classes because I expect that the borrower could make a loan partially to an offer. For example, John offers 500, and Christina borrows 100 of 500, and Bhagy borrows 200 of the remaining. After those loans have been made, the offer is still visible on the market. In this case, its amount should be 200. 

An Offer would disappear from the market place after all of its amount has been borrowed.

I hope these make sense. I'd reply tomorrow because it's too late in Japan.

Thanks,

**Comment by inariDeeTee** [comment]
Yes, duplication was my other concern so that's fine as it is. Could you just add final keyword to totalAmount in Loan and a getAmountLeftToPay method? I think that would probably be useful to have.

**Comment by st2180** [comment]
We don't have time to implement to repay, so I don't think we need getAmountLeftToPay. However, I think it'd be nice to show the semantics of the class by adding the method. I also add Offer.borrow to explicitly show the semantics.

**Comment by inariDeeTee** [comment]
That's great, yes it won't necessarily be used but good to have those in there.

**Review by inariDeeTee — APPROVED** [review]

**Pull request merged**
