### PR TITLE
Improve the test framework in a way that makes the framework to disco…

### PR DESCRIPTION
**Pull request by st2180**
…ver a test method by itself.

### CODE REVIEW

**Review by tp757 — APPROVED** [review]
Hi  Shinichi, I am happy to merge this but was wondering a few things, would it be possible to add an example of how to use the Assert methods in the test example? Also could the AssertEquals method have this line instead Objects.equals(expected + System.lineSeparator(), actual) then it may be slightly easier to use?

Finally, are you planning expand this framework any further during this Sprint?

**Comment by st2180** [comment]
Hello Thomas, 

I'll add some more examples for the assertions and tests later.

Sorry, could you explain a little bit more about this?

_could the AssertEquals method have this line instead Objects.equals(expected + System.lineSeparator(), actual) then it may be slightly easier to use?_

I don't have any plans to expand it at this moment as long as I don't have a request to do.

**Comment by tp757** [comment]
Ok cool, shall I mark it as complete on the Trello board then?

In regards to the line of code I referred to, it is more of case that if you are testing output from the command line, this line would be useful, so then when the method is called you wouldn't need the part in italics newbank.test.NBUnit.AssertEqual("Main: 1000.0" + _System.lineSeparator(),_ bhagy)

However, then I guess you would have to have more than one method to test when objects are equal, one for the command line output, and another for methods than don't output like this. So probably just ignore that. 

Cheers 
Thomas

**Comment by st2180** [comment]
Sorry for the late reply. I understand your point. The AssertEqual is a general assertion where any kinds of equality can be tested. As you said, an addition assertion dedicated to asserting a string following a new line character can be defined when the test pattern appears more often. Thank you for your idea!

**Pull request merged**
