### PR TITLE
Standard messages ch2333

### PR DESCRIPTION
**Pull request by cheb2333**
Standardised error message centrally, so that any new response with status failed or invalid request starts with "FAIL:"
Consolidated cases for success messages
Modified test cases accordingly

### CODE REVIEW

**Comment by cheb2333** [comment]
I tried to use a nice and general solution to keep messages clean, but this was only possible for failed and invalid responses, as we use the successful responses for listing entries as well. I think we should split up this functionality into successful (for when an operation was done) and another type like VIEW (for when a predetermined list of descriptions is showed), but I'm not sure if I should do this now or if that should be another task.

**Comment by inariDeeTee** [comment]
Hi Cornelia, I think it should be fairly straightforward to split SUCCEEDED returns into two types so if you could do that now that would be great. Potentially responses that return descriptions only could be classed as HELP responses instead, since they are essentially helping the user rather than providing any feedback about user actions. I think either of these options would be fine.

**Comment by cheb2333** [comment]
Hi Heather, I introduced a new type VIEWED now, as HELP is already used for calling the help on any given command. I think I found all the different places to change now, as I didn't find any issues during manual and automatic tests, but please let me know if you find anything that I missed.

**Comment by inariDeeTee** [comment]
All the responses look fine, but there seems to be a bug in the diff for NewBankClientHandler. I can only see the one change but it's showing up as a whole file change. Is this the same on your end? I had a quick google and it might be an IntelliJ bug (which I believe is the IDE you're using), but could you have a check to see if you're having the same issue?

**Comment by cheb2333** [comment]
Sorry about that. Yes, in the online view it shows the whole file as changed for me as well, but I only modified the switch-case statement for the logout and commands responses (when I commited it only showed me those changes in the IDE). I've been using IntelliJ for a while and this issue is rare, I think, but I did make a few changes back and forth in this file an it might have been cleaner to just go back to the original and then change the two lines...

**Comment by inariDeeTee** [comment]
Very strange, but at least we know what's (probably) causing the issue! Since we're still waiting on @tp757 's implementation of BORROW, it might be best to wait until his is merged and then rebase on the updated sprint5 branch, and do any other file changes you need to at the same time.

**Comment by inariDeeTee** [comment]
Thomas' branch has been merged now, so please go ahead and make changes as necessary.

**Comment by cheb2333** [comment]
Sorry for the delay, everything should be set now.

**Review by inariDeeTee — APPROVED** [review]

**Comment by inariDeeTee** [comment]
Thanks Cornelia, that's great. I was just a bit worried considering the circumstances at the moment!

**Pull request merged**
