### PR TITLE
Refactored double to BigDecimal for account balance

### PR DESCRIPTION
**Pull request by cheb2333**
Implementation for the issue
"Stop floating point errors in calculations by no longer using double"

Changed the type of opening balance and modified the constructor so that any given double is saved as BigDecimal and can then savely be used for calculations

### CODE REVIEW

**Review by tp757 — COMMENTED** [review]
Hi Cornelia, as the method takes any double, do you think we also need to set the scale of the big decimal it produces to 2?

**Comment by cheb2333** [comment]
Hi Thomas, I figured that we would only need to worry about scaling once we start calculating with it (actually only once we implement some form of interest etc.) and would have just scaled it to 2 for printing for now (to keep the stored value even more exact). But either way would be fine with me.

**Comment by tp757** [comment]
I am thinking more simply than interest, if the customer transfers in/out of their account, the money in will also need to be changed into a big decimal then added/subtracted from the opening balance. My preference would be a private method that takes a double converts it into big double and ensures that it has 2 decimal places, then it could be reused in the future, let me know what you think?

**Comment by cheb2333** [comment]
You make a good point about reuseablity, so I have created a separate method for the conversion. I had to modify the tests accordingly, as this change also took care of the issue of not printing two decimal spaces. I left the rounding type as default, as that is the commonly used one (using the bankers' rounding algorithm).

**Review by tp757 — APPROVED** [review]
Awesome, nice work

**Pull request merged**
