### PR TITLE
As a user I want to be able to transfer money to other users so that I can pay my bills more easily.

### PR DESCRIPTION
**Pull request by st2180**
I reopened a pull request after having added fixes.

### CODE REVIEW

**Review by tp757 — CHANGES_REQUESTED** [review]
Hi Shinichi, really nice functionality, however can it be tweaked so that the payer does not find out anything about the recipients accounts please? Otherwise, it would reveal way to much about another customer's financial situation. You could leave what you have done though in the case where the customer uses PAY to move money to another of their own bank accounts.

**Comment by st2180** [comment]
Hi Thomas, thank you for your comment. Should I change the confirmation message in a way that account information doesn't have balance? Should I exclude an account name as well? Anyway, it's a huge fraw!

**Comment by st2180** [comment]
I've just removed the balance information from the account information of a payee. Could you check it out, please?

**Review by tp757 — APPROVED** [review]
Thanks Shinichi

**Pull request merged**
