### PR TITLE
Confirm default currency ch2333

### PR DESCRIPTION
**Pull request by cheb2333**
Confirmation prompt added for new accounts with default currency

### CODE REVIEW

**Review by inariDeeTee — CHANGES_REQUESTED** [review]
Looks good. Good idea to add the runNewAccount method as that makes tests a bit neater - could you also update the other createNewAccount tests as well please? 
Also could you change the name of defaultCurrency to usedDefaultCurrency, just to make it clearer what the variable is used for.

**Comment by cheb2333** [comment]
Hi Heather, thanks for your comments. I'm happy to rename the variable, but not sure about the other tests. As the confirmation prompt is only called when no currency is given (and when that point in the code is reached without failing before it), I think I've changed all the testcases it applies to. In the other ones the new method is not applicable in my opinion, as there is only the standard first input and no confirmation to deal with. So I'm unsure what exactly to change at this point. Could you clear that up for me?

**Comment by inariDeeTee** [comment]
Hi Cornelia, sorry I misread the method and you are right there is no need to change the other tests. Could you delete the declarations for command in the tests you have changed since these aren't used now?

**Comment by cheb2333** [comment]
Sorry, totally missed those. Of course.

**Comment by inariDeeTee** [comment]
No worries, it's easily done!

**Review by inariDeeTee — APPROVED** [review]

**Pull request merged**
