### PR TITLE
HELP/COMMANDS now prints command names only, must use <COMMAND> -?, -…

### PR DESCRIPTION
**Pull request by sjt-85**
…h, -help for command description

Precise control of the command help.

Problem:
Showing all the commands and their descriptions at the same time might look verbose.

Solution:
1. The menu or COMMANDS command only show the names of the commands.
2. The description of a command is shown only when an invalid parameter is typed by a user.

### CODE REVIEW

**Comment by st2180** [comment]
Hi Simon, It is so quick to finish it! 
I'd like to talk about the implementation a little. In this current Command pattern scheme, the parsing of the command argument is delegated to each command implementation, and each command implementation can indicate to the Invoker whether its argument is valid or not. I think what the Invoker react for the invalid argument would be to switch in the formatResponse method like the following. This also covers the help patterns from 2 to 5.

`switch(response.getType()) {`
`case InvalidRequest: return response.getDescription() `
`+ System.lineSeparator() +System.lineSeparator() + command.getCommandName() + " " +command.getDescription();`
`default: return response.getDescription();`
`}`

However, we need to manage to pass the command object from the dispatch to the formatResponse as well.

**Comment by sjt-85** [comment]
Hi Shinichi,

Something like this?  I'm at work so can't test this code until later hence posting it here rather than committing to my branch.

NewBankClientHandler.java

    public void processRequests(CustomerID id) throws IOException {
      // keep getting requests from the client and processing them
      while (true) {

        String request = in.readLine();
        if (request == null) break; // fall here when called by test.

        var parameter = NewBankCommandParameter.create(id, request);
        if (parameter == null) continue;

        out.println(formatResponse(commands.get(parameter.getCommandName()), dispatch(parameter)));

        if (parameter.getCommandName().equals("LOGOUT")) return;
      }
    }
  

    private NewBankCommandResponse runCommand(NewBankCommandParameter parameter) {
      if (commands.containsKey(parameter.getCommandName())) {

        // check if user is requesting help
        if (parameter.getCommandArgument().matches("\\s*-([hH?]|help|HELP)\\s*$")) {
          return NewBankCommandResponse.Help();
        } else {
          return commands.get(parameter.getCommandName()).run(parameter);
        }
	
      } else {
        return NewBankCommandResponse.invalidRequest("FAIL");
      }
    }
  

    private static String formatResponse(INewBankCommand command, NewBankCommandResponse response) {
      switch (response.getType()) {
      case HELP:
      case INVALIDREQUEST:
        return response.getDescription().isBlank()
               ? getHelpInfo(command);
               : response.getDescription()
                   + System.lineSeparator()
                   + System.lineSeparator()
                   + getHelpInfo(command);
    
      default: return response.getDescription();
      }
    }


    private static String getHelpInfo(INewBankCommand command) {
      return (command != null)
             ? command.getCommandName() + " " + command.getDescription()
             : "Unrecognized command";
    }

**Comment by st2180** [comment]
Hi Simon, it really cool to call getHelpInfo! Also, I think that adding HELP is a nice idea! It allows us to control messages more precisely. I'd like to make a point a little bit.

`out.println(formatResponse(commands.get(parameter.getCommandName()), dispatch(parameter)));`

This line would crash when an unrecognized command is passed, so I think dispatch should return the recognized command or null in addition to String. The formatResponse should also be changed to accept the return value.

**Comment by inariDeeTee** [comment]
Hi Simon, could you add a else if statement at line 131 to check for null parameters? That way we can have a specific error message for no command entered (i.e. user presses enter), and then in the else block that error message can be specifically for invalid command entered.

**Comment by sjt-85** [comment]
Hi Shinichi,

I've added an INewBankCommand field to the NewBankCommandResponse class so we can tie things up on the output side.  Not sure if the called command or the original NewBankCommandParameter would be most appropriate?

I've also added a constant static NewBankCommandResponse object for the empty response, as occurs in the scenario Heather mentioned above, so submitting nothingness just returns nothingness!

**Comment by st2180** [comment]
Sorry for the late reply because of the time gap. I understand that it was not straightforward to return heterogeneous types from the dispatch method. We could use output parameters or Tuple in C# or pointers in C++. However, Java doesn't have any of them! This weak functionality of Java makes me stuck often as well. 

On the other hand, the needs of the Command object in formatResponse is an internal implementation issue of the Invoker. So, it would be better to encapsulate it and keep the API of NewBankCommandResponse simple. How about defining an internal class and wrap those return values in order to return from the dispatch? 

`

    class DispatchResult {

      public DispatchResult(INewBankCommand command, NewBankCommandResponse response) {

        this.command = command;

        this.response = response;

      }

      private INewBankCommand command;
      private NewBankCommandResponse response;
      public INewBankCommand getCommand() {
        return command;
      }
      public NewBankCommandResponse getResponse() {
        return response;
      }
    }
`

Sorry to bother you for this kind of small details. I can do this instead when I make a pull request probably today because it's too late time in the UK.

**Review by st2180 — APPROVED** [review]

**Pull request merged**
