### PR TITLE
Transferreq tp

### PR DESCRIPTION
**Pull request by tp757**
Implemented transfer command and included tests

### CODE REVIEW

**Review by cheb2333 — CHANGES_REQUESTED** [review]
Hi Thomas, well done on the functionality! Overall I like the structure you used for the command and I only have a few small issues to address:

- I noticed that your method ValidAmount in TransferCommand starts with a captial letter. This is not good style, so could you please rename it to start with a small letter instead?

- According to the coding guidelines that we chose to adhere to, wildcard imports are not allowed (e.g. import newbank.server.Commands.*) - could you fix that in both NewBankServer and the ServerTestScenarios please? There should also be a setting in your IDE that ensures that no wildcards are used by default, which might make it easier for the future.

- Finally, I noticed that it is not allowed to use "" when putting in the account name to your command. I don't mind it, but as that is the syntax used for creating a new account, I think it should be noted in the command to not confuse users (or you could trim the "" from the input string and therefore allow them, which ever option you like better).

**Comment by tp757** [comment]
Hi Cornelia, I have made the changes, for the last one I took out the quotations marks like you said, so the user can choose whether to use them or not, I also added a few instances of this to the tests

**Comment by tp757** [comment]
I can also change it so it is a regex pattern and it picks up between the " ", without any slashes, but to be honest delimiting by a slash is so much easier to type into the command line than using quotations marks

**Comment by cheb2333** [comment]
Thank you, that's great. I agree with you that it's easier to use the slash and I think that's fine, I just wanted to avoid making the users have quotation marks for one command and then forcing them to not use them in the next, as that feels crude.

**Review by cheb2333 — APPROVED** [review]

**Pull request merged**
