### PR TITLE
Workingbranch st2180 2

### PR DESCRIPTION
**Pull request by st2180**
"Decoupling command implementations from NewBank class" finished and merged to the work of Thomas.

### CODE REVIEW

**Review by cheb2333 — COMMENTED** [review]
Hi Shinichi, amazing work! I'm still doing some more testing, but I noticed one issue that I would like to address. I've seen that you use a lot of classifed names (newbank.server.Customer) instead of importing the classes. To my knowledge, using imports is the Java standard and so I was wondering if you would might changing this? (In most IDEs you can have it done automatically)

**Comment by st2180** [comment]
Hi Cornelia, I also don't like the lengthy classified names, but IntelliJ IDEA tells me to write in such a way. Is it because the structure of the directory doesn't match the package structure?

**Comment by cheb2333** [comment]
I'm using IntelliJ as well and for me it even gives me the option to automatically import any such statements, so I guess that it has to do with your setup. Which folder do you have as sources root? I had to manually set it to the NewBank folder, so that newbank and everything below are considered packages.

**Comment by st2180** [comment]
You are correct. It was a setting problem. Now, the code looks better. Thank you!

**Review by cheb2333 — APPROVED** [review]
Great, glad to hear it.

**Pull request merged**
