### PR TITLE
Implementmove hs2158

### PR DESCRIPTION
**Pull request by inariDeeTee**
Implemented MOVE replacing TRANSFER, with reference to original protocol for order of command line arguments.

### CODE REVIEW

**Comment by st2180** [comment]
This pull request goes toward the master. Could you fix it out?

**Comment by inariDeeTee** [comment]
Fixed the base branch - sorry!

**Comment by st2180** [comment]
Hi Heather, I'm trying to merge your pull request now, but the code can't pass the tests on my side. Do the tests passed on you side?

**Comment by inariDeeTee** [comment]
Hi Shinichi, the tests should work now so please take a look.

**Review by st2180 — APPROVED** [review]

**Pull request merged**
