### PR TITLE
Added currency to accounts

### PR DESCRIPTION
**Pull request by cheb2333**
Implemented a new enum for currency and added it to account, with GBP being the standard if no other currency is given. Modified the NEWACCOUNT method to take an optional third argument (currency) and added an error message if an invalid currency is used.
Modified existing test to fit the new output and created new tests for NEWACCOUNT use cases.

### CODE REVIEW

**Review by tp757 — CHANGES_REQUESTED** [review]
Hi Cornelia, really sorry but I had two pull requests around the same time, and I picked up the account types pull request first and you have both changed the add new accounts method, and they both do different things, so cannot be merged. If you have time today, would you be able and add the currency to the separate account types? If not we could just leave the currency class in there and look to implement this next sprint.

**Comment by cheb2333** [comment]
Hi Thomas, no worries, I planned some time for today, so I'll give it a try now.

**Comment by cheb2333** [comment]
I managed to put the two changes together, but there are two things I want to note:
- you can now only create an account with a different currency if you also give it a custom name (this is due to our current implementation and I think it should still be alright for the moment)

- I noticed that whenever there is any error in creating a new account our program just returns "FAIL", which makes it difficult to figure out which of the many arguments entered is causing the problem. So I have added a message in case the currency is invalid, but maybe we should also add some help messages for wrong account type and account already exists?

**Review by tp757 — CHANGES_REQUESTED** [review]
Thank you for making these changes, just one slight alteration though please, are you able to update the Protocol to confirm that the account name is not optional for non-GBP accounts please?

**Comment by tp757** [comment]
Also I definitely agree about the other fail messages, and we could add other messages, such as the account already exists or an invalid account type

**Comment by cheb2333** [comment]
Fixed the protocol entry.

Can we make a new task for the fail messages, though? I would prefer not to have to spend another hour or so going through all options and testing them today.

**Review by tp757 — APPROVED** [review]
Yes, are you able to add a new task to Trello for the updated messages, so it can be done during another sprint please?

**Pull request merged**
