### PR TITLE
Replaced "\n" with System.lineSeparator()

### PR DESCRIPTION
**Pull request by inariDeeTee**
This project is now a No "\n" Zone.

### CODE REVIEW

**Review by cheb2333 — CHANGES_REQUESTED** [review]
Hi Heather, looks good so far. For me as a Windows user some of the tests didn't pass anymore, however, and upon closer checking I found that there are still two occurances of "\n" in NewAccountCommand (and also in NBUnit, but they should not affect the tests). Please replace those as well.

**Comment by inariDeeTee** [comment]
They are all changed on my local repository so not sure what is going on there, I will investigate and get back to you.

**Comment by inariDeeTee** [comment]
I think I missed the shift key when trying to save all files last night - I really need to get around to fixing my left shift key.

**Review by cheb2333 — APPROVED** [review]
No worries, it happens. All good now!

**Pull request merged**
